[project]
name = "threedscriptors"
version = "0.1.0"
description = ""

authors = [
    { name = "Steffen Wedig", email = "snw30@cam.ac.uk" },
]

readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.5.1",
    "ase>=3.24.0",
    "rdkit>=2024.9.4",
    "wandb",
    "pydantic",
    "pydantic_yaml",
    "mace-torch>=0.3.16",
    "umap-learn",
    "torch-sim-atomistic",
    "zarr==2.18.7",
    "graph-longrange",
    "cuequivariance-torch==0.9.1",
    "cuequivariance==0.9.1",
    "cuequivariance-ops-torch-cu12==0.9.1",
    "pymatgen>=2026.3.23",
]


mols  = ["polaris-lib>=0.11.4",
    "molfeat",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
lint.select = ["I", "UP", "F", "E", "W", "C90", "B", "A", "RUF"]
lint.ignore = ["E501", "B008"]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest",
    "ty>=0.0.32",
]
[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
graph-longrange = { git = "https://github.com/WillBaldwin0/graph_electrostatics.git" }
torch-sim-atomistic = { git = "https://github.com/TorchSim/torch-sim.git", branch = "main"}
torch = { index = "pytorch-cu126" }

[tool.ty.environment]
root = ["./threedscriptors"]
