kind: encoder_decoder
embedding_preprocess_config:
  input_irreps: 128x0e+128x1o+128x0e
  pseudoscalar_dimension: 64
  chiral_embedding_dimension: 64
  pseudoscalars: true
  equivariant_rms_normalization: true
  gated: true
encoder_config:
  N_layers: 4
  attention_layer_config:
    dim_feedforward: 1024
    dropout: 0.3
    embedding_dim: 320
    num_heads: 8
  d_geo: 16
  d_pair: 64
decoder_config:
  N_layers: 4
  attention_layer_config:
    dim_feedforward: 1024
    dropout: 0.3
    embedding_dim: 320
    num_heads: 8
  d_descriptor: 320
  d_geo: 16
  d_pair: 64
positional_encoding_config:
  N_radial_basis_functions: 16
  d_projection: 64
  distance_cutoff: 32.0
  basis_function_config:
    kind: bessel
global_aggregator_config:
  aggregator_type_config:
    aggregator_type: attention
    attn_dropout: 0.3
    num_heads: 8
  global_molecular_descriptor_dropout: 0.0
  input_dim: 320
  output_dim: 320
