batch_size: 192
dataset_path:
  /scratch/s5f/wedigs.s5f/datasets/tmqm
epochs: 10
learning_rate: 0.0005
max_grad_norm: 1.0
model_config_path: /home/s5f/wedigs.s5f/3DMolecularDescriptors/training_runs/example_dir/architecture_config.yaml
output_base: /scratch/s5f/wedigs.s5f/training_runs
noise_level: 0.3
run_group: transition_metal_complexes
split_config:
  N_folds: null
  N_repeats: null
  shuffle: true
  strategy: single
  train_val_ratios:
  - 0.8
  - 0.2
total_steps: null
training_name: tmc_0
wandb_active: true
weight_decay: 0.001
