"""Generate the 2x2 chiral-classifier ablation (pseudoscalars x focal loss).

Four runs over the two design choices baked into the base chiral config:

    pseudoscalars in {on, off}  x  loss in {focal+balanced-alpha, plain CE}

    ps_focal   : pseudoscalars on,  focal loss        (the proposed model)
    nops_focal : pseudoscalars off, focal loss        (pseudoscalar control)
    ps_ce      : pseudoscalars on,  plain CE          (focal/imbalance control)
    nops_ce    : pseudoscalars off, plain CE          (joint baseline / floor)

With all four on the same stratified split, a gain on the rare chiral classes
(axial/helical/planar) is attributable to pseudoscalars (ps - nops) and to focal
loss (focal - ce) independently.

Each run dir gets a ``training_config.yaml`` + ``architecture_config.yaml`` under
``configs/training/chiral_cat_ablation/<run>/``. The configs are edited as raw
dicts (not parsed pydantic objects) so the no-pseudoscalar variants re-run the
dimension cascade from scratch — ``output_irreps_dim`` drops 384 -> 256 and the
encoder / aggregator dims follow — instead of baking in the on-pseudoscalar dims.

Generate, then submit all four packed onto one Booster node::

    uv run python scripts/generate_chiral_ablation_configs.py
    uv run python scripts/submit_job.py \\
        configs/training/chiral_cat_ablation/*/training_config.yaml \\
        --group chiral_cat_ablation
"""

from __future__ import annotations

import copy
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
BASE_DIR = REPO_ROOT / "configs" / "training" / "chiral_cat"
OUT_DIR = REPO_ROOT / "configs" / "training" / "chiral_cat_ablation"
OUTPUT_BASE = Path("/p/scratch/mace/wedig1/training_runs/chiral_cat_ablation")
RUN_GROUP = "chiral_cat_ablation"

# (run_name, pseudoscalars_on, focal_on)
RUNS: tuple[tuple[str, bool, bool], ...] = (
    ("ps_focal", True, True),
    ("nops_focal", False, True),
    ("ps_ce", True, False),
    ("nops_ce", False, False),
)

_HEADER = (
    "# Auto-generated by scripts/generate_chiral_ablation_configs.py\n"
    "# 2x2 chiral-classifier ablation: pseudoscalars x focal loss. Do not edit\n"
    "# by hand; edit the base configs/training/chiral_cat/ + the generator.\n"
)


def _load(path: Path) -> dict:
    with open(path) as fh:
        return yaml.safe_load(fh)


def _dump(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as fh:
        fh.write(_HEADER)
        yaml.safe_dump(data, fh, sort_keys=False, default_flow_style=False)


def build_run(name: str, pseudoscalars: bool, focal: bool) -> None:
    base_arch = _load(BASE_DIR / "architecture_config.yaml")
    base_train = _load(BASE_DIR / "training_config.yaml")

    arch = copy.deepcopy(base_arch)
    ep = arch["embedding_preprocess_config"]
    ep["pseudoscalars"] = pseudoscalars
    if not pseudoscalars:
        # No parity-odd chiral block -> the cascade recomputes output_irreps_dim
        # (256) and the encoder/aggregator dims from it on load.
        ep["chiral_embedding_dimension"] = 0

    train = copy.deepcopy(base_train)
    train["training_name"] = f"chiral_{name}"
    train["run_group"] = RUN_GROUP
    train["output_base"] = str(OUTPUT_BASE)
    train["model_config_path"] = (
        f"./configs/training/chiral_cat_ablation/{name}/architecture_config.yaml"
    )
    if focal:
        train["classification"] = {"focal_gamma": 2.0, "class_balanced_alpha": True}
    else:
        # Plain (unweighted) cross-entropy: gamma 0 + no class weighting.
        train["classification"] = {"focal_gamma": 0.0, "class_balanced_alpha": False}

    run_dir = OUT_DIR / name
    _dump(run_dir / "architecture_config.yaml", arch)
    _dump(run_dir / "training_config.yaml", train)
    print(
        f"{name}: pseudoscalars={pseudoscalars} focal={focal} -> {run_dir}"
    )


def main() -> None:
    for name, ps, focal in RUNS:
        build_run(name, ps, focal)


if __name__ == "__main__":
    main()
