"""The bundle and dataset format (``BENCHMARK_DATA_FORMAT.md`` §10).

A bundle is a table (``dataset.yaml``, ``table.parquet``, ``provenance.yaml``)
with one row per stereoisomer; a dataset is a zarr with the same three files
beside it and one table row per structure. This subpackage owns the schema
(:mod:`spec`, :mod:`provenance`), identity assignment (:mod:`identity`), the
source-row merge every SMILES preparer shares (:mod:`aggregation`), the
invariants (:mod:`validate`), the disk io of the three files (:mod:`bundle`)
and the bundle -> dataset row expansion (:mod:`expansion`). It is torch-free.
"""

from remedi.data_handling.bundle.aggregation import (
    AGGREGATION_NOTICE,
    DUPLICATE_LABEL_TIE,
    DUPLICATE_SMILES,
    INVALID_SMILES,
    MEASUREMENT_COUNT_COLUMN,
    MISSING_LABEL,
    SMILES_FILTER,
    AggregatedRows,
    FilterOutcome,
    LabelAggregationError,
    MergedRows,
    aggregate_by_canonical_smiles,
    aggregate_label,
    check_row_accounting,
    filter_source_smiles,
    merge_source_rows,
)
from remedi.data_handling.bundle.bundle import (
    DATASET_CONFIG_FILENAME,
    FORMAT_VERSION,
    PROVENANCE_FILENAME,
    SPEC_FILENAME,
    TABLE_FILENAME,
    Bundle,
    BundleValidationError,
    content_hash_of_table,
    discover_bundles,
    discover_datasets,
    is_dataset_directory,
    normalize_table,
    read_bundle,
    read_provenance,
    read_spec,
    read_table,
    sha256_of_file,
    structures_identity,
    write_bundle,
    write_table_files,
)
from remedi.data_handling.bundle.expansion import (
    CONFORMER_EMBEDDING_FAILED,
    ENANTIOMER_PARTNER_FAILED,
    ExpandedDataset,
    expand_to_structures,
)
from remedi.data_handling.bundle.identity import (
    CanonicalSmilesPair,
    IdentityTable,
    SmilesParseError,
    assign_identity,
    canonical_smiles_pair,
    mirror_isomeric_smiles,
)
from remedi.data_handling.bundle.provenance import (
    BundleCounts,
    BundleOutputs,
    BundleProvenance,
    ConformerGenerationRecord,
    FileHash,
    PreparerRecord,
    SourceRecord,
    TableOutputRecord,
    git_head_sha,
)
from remedi.data_handling.bundle.spec import (
    METRICS_BY_TASK_TYPE,
    SPLIT_VALUES,
    DatasetSpec,
    EvalMetric,
    EvaluationSpec,
    GeometryOrigin,
    IdentityLabelTransform,
    LabelColumn,
    LabelTransform,
    Log10LabelTransform,
    SplitGroup,
    metrics_with_headline,
)
from remedi.data_handling.bundle.validate import (
    count_stereoisomer_straddling_constitutions,
    has_assigned_tetrahedral_centre,
    stereochemistry_from_frame,
    structure_problems,
    tetrahedral_stereo_smiles,
    validate_table,
)

__all__ = [
    "AGGREGATION_NOTICE",
    "CONFORMER_EMBEDDING_FAILED",
    "DATASET_CONFIG_FILENAME",
    "DUPLICATE_LABEL_TIE",
    "DUPLICATE_SMILES",
    "ENANTIOMER_PARTNER_FAILED",
    "FORMAT_VERSION",
    "INVALID_SMILES",
    "MEASUREMENT_COUNT_COLUMN",
    "METRICS_BY_TASK_TYPE",
    "MISSING_LABEL",
    "PROVENANCE_FILENAME",
    "SMILES_FILTER",
    "SPEC_FILENAME",
    "SPLIT_VALUES",
    "TABLE_FILENAME",
    "AggregatedRows",
    "Bundle",
    "BundleCounts",
    "BundleOutputs",
    "BundleProvenance",
    "BundleValidationError",
    "CanonicalSmilesPair",
    "ConformerGenerationRecord",
    "DatasetSpec",
    "EvalMetric",
    "EvaluationSpec",
    "ExpandedDataset",
    "FileHash",
    "FilterOutcome",
    "GeometryOrigin",
    "IdentityLabelTransform",
    "IdentityTable",
    "LabelAggregationError",
    "LabelColumn",
    "LabelTransform",
    "Log10LabelTransform",
    "MergedRows",
    "PreparerRecord",
    "SmilesParseError",
    "SourceRecord",
    "SplitGroup",
    "TableOutputRecord",
    "aggregate_by_canonical_smiles",
    "aggregate_label",
    "assign_identity",
    "canonical_smiles_pair",
    "check_row_accounting",
    "content_hash_of_table",
    "count_stereoisomer_straddling_constitutions",
    "discover_bundles",
    "discover_datasets",
    "expand_to_structures",
    "filter_source_smiles",
    "git_head_sha",
    "has_assigned_tetrahedral_centre",
    "is_dataset_directory",
    "merge_source_rows",
    "metrics_with_headline",
    "mirror_isomeric_smiles",
    "normalize_table",
    "read_bundle",
    "read_provenance",
    "read_spec",
    "read_table",
    "sha256_of_file",
    "stereochemistry_from_frame",
    "structure_problems",
    "structures_identity",
    "tetrahedral_stereo_smiles",
    "validate_table",
    "write_bundle",
    "write_table_files",
]
